name: Cleanup Workflow Runs
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Type the name of the Repository you want to delete workflows of"
        default: ""
        required: true
      days_old:
        description: "Which Workflows to Delete (Days)"
        default: "7"
        required: true

jobs:
  clean-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: Comp-Labs
          repo: ${{ github.event.inputs.repository }}
          days_old: ${{ github.event.inputs.days_old }}
